---
title: "PY4LS22.01"
subtitle: "Python for Life Sciences -- A Step by Step Guide for Life Scientists"
author: "Md. Jubayer Hossain <br/> Founder, CHIRAL Bangladesh"
output:
  xaringan::moon_reader:
    css: ["default", "css/chiral.css", "css/chiral-fonts.css"]
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "65%", cache = FALSE)
library(tidyverse)
library(babynames)
```

## Hi & welcome!


---
class: inverse center middle

# Introduction to Python

--

---
## What is Python? 
- Python is an interpreted, high-level, general-purpose programming language. 
- Python's design philosophy emphasizes code **readability** with its notable use of significant whitespace


---
## Key Points 
- Designed by: [Guido van Rossum](https://en.wikipedia.org/wiki/Guido_van_Rossum)
- Typing discipline: Duck, dynamic, gradual
- Stable release: 3.8.2 / 24 February 2020; 25 days ago
- Preview release: 3.9.0a4 / 26 February 2020; 23 days ago
- Paradigm: Multi-paradigm: functional, imperative, object-oriented, reflective


---
## Why Python? 
- Python Is Free and Open-Source

--

- Python Is Popular, Loved, and Wanted

--

- Python Has a Friendly and Devoted Community

--
- Python Has Elegant and Concise Syntax

--

- Python Is Multi-Platform

--

- Python Supports Multiple Programming Paradigms 

--

- Python Offers Useful Built-In Libraries

--

- Python Has Many Third-Party Packages

--

- Python Is a General-Purpose Programming Language

--

- Python Plays Nice with Others

--



---
## Why Python Rocks for Research? 
- Holistic Language Design
--

- Readability

--

- Balance of High Level and Low Level Programming

--

- Language Interoperability

--

- Documentation System

--

- Hierarchical Module System

--

- Data Structures

--

- Available Libraries

--
- Testing Framework

--

---
class: inverse center middle

# Python Libraries for Scientific Computing 

--

---
## Data Analysis / Data Science Packages 
- NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
- https://numpy.org/
